version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: FluentValidation.AspNetCore
    versions:
    - 10.0.0
    - 10.0.1
    - 10.0.2
    - 10.0.3
    - 10.0.4
  - dependency-name: MassTransit.Extensions.DependencyInjection
    versions:
    - 7.1.7
  - dependency-name: MassTransit.RabbitMQ
    versions:
    - 7.1.7
  - dependency-name: AspNetCore.HealthChecks.UI.Client
    versions:
    - 5.0.1
  - dependency-name: Hangfire.Core
    versions:
    - 1.7.19
    - 1.7.20
  - dependency-name: Hangfire.AspNetCore
    versions:
    - 1.7.19
    - 1.7.20
  - dependency-name: Microsoft.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.Tools
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Mvc.Testing
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Mvc.NewtonsoftJson
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.Design
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.TestHost
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.Extensions.Http.Polly
    versions:
    - 5.0.1
  - dependency-name: Microsoft.Extensions.Logging
    versions:
    - 5.0.0
