version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Run Tests
          command: |
            mkdir -p /tmp/coverage
            docker-compose -f docker-compose.tests.yml up --build --abort-on-container-exit domain-unit-test
            docker cp domain-unit-test:/coverage.xml /tmp/coverage/domain-unit-test.xml
            docker-compose -f docker-compose.tests.yml down
      - store_artifacts:
          path: /tmp/coverage
      - codecov/upload:
          file: /tmp/coverage/*.xml
    
