// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestOkur.Data;

namespace TestOkur.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190517102639_SmsGroupdAndContactAuditable")]
    partial class SmsGroupdAndContactAuditable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Relational:Sequence:.appsettings_seq", "'appsettings_seq', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.exam_type_optical_form_seq", "'exam_type_optical_form_seq', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.exam_types_seq", "'exam_types_seq', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.exams_seq", "'exams_seq', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.form_lesson_sections_seq", "'form_lesson_sections_seq', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.lessons_seq", "'lessons_seq', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.optical_form_definitions_seq", "'optical_form_definitions_seq', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.optical_form_text_locations_seq", "'optical_form_text_locations_seq', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.optical_form_types_seq", "'optical_form_types_seq', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.subjects_seq", "'subjects_seq', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.units_seq", "'units_seq', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.user_seq", "'user_seq', '', '1', '10', '', '', 'Int64', 'False'");

            modelBuilder.Entity("TestOkur.Domain.Model.CityModel.City", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.ToTable("cities");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.CityModel.District", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id");

                    b.Property<long?>("city_id")
                        .HasColumnName("city_id");

                    b.HasKey("Id")
                        .HasName("pk_districts");

                    b.HasIndex("city_id")
                        .HasName("ix_districts_city_id");

                    b.ToTable("districts");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ClassroomModel.Classroom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnName("created_on_utc");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnName("updated_on_utc");

                    b.Property<int>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_classrooms");

                    b.ToTable("classrooms");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ExamModel.AnswerFormFormat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_answer_form_format");

                    b.ToTable("answer_form_format");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ExamModel.Exam", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:HiLoSequenceName", "exams_seq")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("ApplicableFormTypeCode")
                        .HasColumnName("applicable_form_type_code");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnName("created_on_utc");

                    b.Property<long?>("ExamBookletTypeId")
                        .HasColumnName("exam_booklet_type_id");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnName("exam_date");

                    b.Property<string>("Notes")
                        .HasColumnName("notes");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnName("updated_on_utc");

                    b.Property<int>("UserId")
                        .HasColumnName("user_id");

                    b.Property<long?>("answer_form_format_id")
                        .HasColumnName("answer_form_format_id");

                    b.Property<long?>("exam_type_id")
                        .HasColumnName("exam_type_id");

                    b.Property<long?>("lesson_id")
                        .HasColumnName("lesson_id");

                    b.HasKey("Id")
                        .HasName("pk_exams");

                    b.HasIndex("ExamBookletTypeId")
                        .HasName("ix_exams_exam_booklet_type_id");

                    b.HasIndex("answer_form_format_id")
                        .HasName("ix_exams_answer_form_format_id");

                    b.HasIndex("exam_type_id")
                        .HasName("ix_exams_exam_type_id");

                    b.HasIndex("lesson_id")
                        .HasName("ix_exams_lesson_id");

                    b.ToTable("exams");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ExamModel.ExamBookletType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_exam_booklet_type");

                    b.ToTable("exam_booklet_type");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ExamModel.ExamScanSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<bool>("ByCamera")
                        .HasColumnName("by_camera");

                    b.Property<bool>("ByFile")
                        .HasColumnName("by_file");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("EndDateTimeUtc")
                        .HasColumnName("end_date_time_utc");

                    b.Property<Guid>("ReportId")
                        .HasColumnName("report_id");

                    b.Property<int>("ScannedStudentCount")
                        .HasColumnName("scanned_student_count");

                    b.Property<string>("Source")
                        .HasColumnName("source");

                    b.Property<DateTime>("StartDateTimeUtc")
                        .HasColumnName("start_date_time_utc");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnName("updated_on_utc");

                    b.Property<long?>("exam_id")
                        .HasColumnName("exam_id");

                    b.HasKey("Id")
                        .HasName("pk_exam_scan_sessions");

                    b.HasIndex("exam_id")
                        .HasName("ix_exam_scan_sessions_exam_id");

                    b.ToTable("exam_scan_sessions");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ExamModel.ExamType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:HiLoSequenceName", "exam_types_seq")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<int>("CreatedBy")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnName("created_on_utc");

                    b.Property<int>("Order")
                        .HasColumnName("order");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_exam_types");

                    b.ToTable("exam_types");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ExamModel.ExamTypeOpticalFormType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:HiLoSequenceName", "exam_type_optical_form_seq")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<long?>("ExamTypeId")
                        .HasColumnName("exam_type_id");

                    b.Property<long?>("optical_form_type_id")
                        .HasColumnName("optical_form_type_id");

                    b.HasKey("Id")
                        .HasName("pk_exam_type_optical_form_types");

                    b.HasIndex("ExamTypeId")
                        .HasName("ix_exam_type_optical_form_types_exam_type_id");

                    b.HasIndex("optical_form_type_id")
                        .HasName("ix_exam_type_optical_form_types_optical_form_type_id");

                    b.ToTable("exam_type_optical_form_types");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.LessonModel.Lesson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:HiLoSequenceName", "lessons_seq")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<int>("CreatedBy")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnName("created_on_utc");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnName("updated_on_utc");

                    b.Property<int>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_lessons");

                    b.HasIndex("UserId")
                        .HasName("ix_lessons_user_id");

                    b.ToTable("lessons");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.LessonModel.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:HiLoSequenceName", "subjects_seq")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<int>("CreatedBy")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnName("created_on_utc");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnName("updated_on_utc");

                    b.Property<long?>("unit_id")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_subjects");

                    b.HasIndex("unit_id")
                        .HasName("ix_subjects_unit_id");

                    b.ToTable("subjects");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.LessonModel.Unit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:HiLoSequenceName", "units_seq")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<int>("CreatedBy")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnName("created_on_utc");

                    b.Property<long?>("LessonId")
                        .HasColumnName("lesson_id");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnName("updated_on_utc");

                    b.Property<int>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasIndex("LessonId")
                        .HasName("ix_units_lesson_id");

                    b.HasIndex("UserId")
                        .HasName("ix_units_user_id");

                    b.ToTable("units");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.OpticalFormModel.Direction", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(100);

                    b.HasKey("Id")
                        .HasName("pk_directions");

                    b.ToTable("directions");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.OpticalFormModel.FormLessonSection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:HiLoSequenceName", "form_lesson_sections_seq")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<int>("FormPart")
                        .HasColumnName("form_part");

                    b.Property<int>("ListOrder")
                        .HasColumnName("list_order");

                    b.Property<int>("MaxQuestionCount")
                        .HasColumnName("max_question_count");

                    b.Property<string>("NameTag")
                        .HasColumnName("name_tag");

                    b.Property<long?>("lesson_id")
                        .HasColumnName("lesson_id");

                    b.Property<long?>("optical_form_type_id")
                        .HasColumnName("optical_form_type_id");

                    b.HasKey("Id")
                        .HasName("pk_form_lesson_sections");

                    b.HasIndex("lesson_id")
                        .HasName("ix_form_lesson_sections_lesson_id");

                    b.HasIndex("optical_form_type_id")
                        .HasName("ix_form_lesson_sections_optical_form_type_id");

                    b.ToTable("form_lesson_sections");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.OpticalFormModel.OpticalFormDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:HiLoSequenceName", "optical_form_definitions_seq")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Description")
                        .HasColumnName("description");

                    b.Property<bool>("HasBoxForStudentNumber")
                        .HasColumnName("has_box_for_student_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(50)
                        .IsUnicode(true);

                    b.Property<string>("Path")
                        .HasColumnName("path");

                    b.Property<int>("StudentNoFillWidth")
                        .HasColumnName("student_no_fill_width");

                    b.Property<int>("StudentNoXInterval")
                        .HasColumnName("student_no_xinterval");

                    b.Property<int>("StudentNoYInterval")
                        .HasColumnName("student_no_yinterval");

                    b.Property<long?>("StudentNumberFillDirectionId")
                        .HasColumnName("student_number_fill_direction_id");

                    b.Property<long?>("TextDirectionId")
                        .HasColumnName("text_direction_id");

                    b.Property<long?>("optical_form_type_id")
                        .HasColumnName("optical_form_type_id");

                    b.Property<long?>("school_type_id")
                        .HasColumnName("school_type_id");

                    b.HasKey("Id")
                        .HasName("pk_optical_form_definitions");

                    b.HasIndex("StudentNumberFillDirectionId")
                        .HasName("ix_optical_form_definitions_student_number_fill_direction_id");

                    b.HasIndex("TextDirectionId")
                        .HasName("ix_optical_form_definitions_text_direction_id");

                    b.HasIndex("optical_form_type_id")
                        .HasName("ix_optical_form_definitions_optical_form_type_id");

                    b.HasIndex("school_type_id")
                        .HasName("ix_optical_form_definitions_school_type_id");

                    b.ToTable("optical_form_definitions");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.OpticalFormModel.OpticalFormTextLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:HiLoSequenceName", "optical_form_text_locations_seq")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<long?>("optical_form_definition_id")
                        .HasColumnName("optical_form_definition_id");

                    b.HasKey("Id")
                        .HasName("pk_optical_form_text_locations");

                    b.HasIndex("optical_form_definition_id")
                        .HasName("ix_optical_form_text_locations_optical_form_definition_id");

                    b.ToTable("optical_form_text_locations");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.OpticalFormModel.OpticalFormType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:HiLoSequenceName", "optical_form_types_seq")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Code")
                        .HasColumnName("code");

                    b.Property<string>("ConfigurationFile")
                        .HasColumnName("configuration_file");

                    b.Property<int>("MaxQuestionCount")
                        .HasColumnName("max_question_count");

                    b.Property<long?>("SchoolTypeId")
                        .HasColumnName("school_type_id");

                    b.HasKey("Id")
                        .HasName("pk_optical_form_types");

                    b.HasIndex("SchoolTypeId")
                        .HasName("ix_optical_form_types_school_type_id");

                    b.ToTable("optical_form_types");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.SchoolType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(100);

                    b.HasKey("Id")
                        .HasName("pk_school_types");

                    b.ToTable("school_types");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ScoreModel.FormulaType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(20);

                    b.HasKey("Id")
                        .HasName("pk_formula_types");

                    b.ToTable("formula_types");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ScoreModel.LessonCoefficient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<float>("Coefficient")
                        .HasColumnName("coefficient");

                    b.Property<long?>("ScoreFormulaId")
                        .HasColumnName("score_formula_id");

                    b.Property<long?>("exam_lesson_section_id")
                        .HasColumnName("exam_lesson_section_id");

                    b.HasKey("Id")
                        .HasName("pk_lesson_coefficients");

                    b.HasIndex("ScoreFormulaId")
                        .HasName("ix_lesson_coefficients_score_formula_id");

                    b.HasIndex("exam_lesson_section_id")
                        .HasName("ix_lesson_coefficients_exam_lesson_section_id");

                    b.ToTable("lesson_coefficients");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ScoreModel.ScoreFormula", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<float>("BasePoint")
                        .HasColumnName("base_point");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnName("discriminator");

                    b.Property<long?>("FormulaTypeId")
                        .HasColumnName("formula_type_id");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnName("updated_on_utc");

                    b.Property<int>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_score_formulas");

                    b.HasIndex("FormulaTypeId")
                        .HasName("ix_score_formulas_formula_type_id");

                    b.ToTable("score_formulas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ScoreFormula");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.SettingModel.AppSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:HiLoSequenceName", "appsettings_seq")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Comment")
                        .HasColumnName("comment");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnName("created_on_utc");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnName("updated_on_utc");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnName("value")
                        .IsUnicode(true);

                    b.HasKey("Id")
                        .HasName("pk_appsettings");

                    b.ToTable("appsettings");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.SmsModel.SmsGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnName("created_on_utc");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_sms_groups");

                    b.ToTable("sms_groups");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.StudentModel.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnName("created_on_utc");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnName("updated_on_utc");

                    b.Property<bool>("UseForSms")
                        .HasColumnName("use_for_sms");

                    b.Property<long?>("student_id")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.HasIndex("student_id")
                        .HasName("ix_contacts_student_id");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.StudentModel.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Notes")
                        .HasColumnName("notes")
                        .HasMaxLength(500);

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnName("updated_on_utc");

                    b.Property<int>("UserId")
                        .HasColumnName("user_id");

                    b.Property<long?>("classroom_id")
                        .HasColumnName("classroom_id");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("UserId")
                        .HasName("ix_students_user_id");

                    b.HasIndex("classroom_id")
                        .HasName("ix_students_classroom_id");

                    b.ToTable("students");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.UserModel.LicenseType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnName("id");

                    b.Property<bool>("CanScan")
                        .HasColumnName("can_scan");

                    b.Property<int>("MaxAllowedDeviceCount")
                        .HasColumnName("max_allowed_device_count");

                    b.Property<int>("MaxAllowedRecordCount")
                        .HasColumnName("max_allowed_record_count");

                    b.HasKey("Id")
                        .HasName("pk_license_types");

                    b.ToTable("license_types");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.UserModel.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:HiLoSequenceName", "user_seq")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SequenceHiLo);

                    b.Property<long?>("CityId")
                        .HasColumnName("city_id");

                    b.Property<int>("CreatedBy")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnName("created_on_utc");

                    b.Property<long?>("DistrictId")
                        .HasColumnName("district_id");

                    b.Property<string>("Notes")
                        .HasColumnName("notes")
                        .HasMaxLength(500);

                    b.Property<int>("SmsBalance")
                        .HasColumnName("sms_balance");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnName("subject_id");

                    b.Property<int>("UpdatedBy")
                        .HasColumnName("updated_by");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CityId")
                        .HasName("ix_users_city_id");

                    b.HasIndex("DistrictId")
                        .HasName("ix_users_district_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ScoreModel.ExamScoreFormula", b =>
                {
                    b.HasBaseType("TestOkur.Domain.Model.ScoreModel.ScoreFormula");

                    b.Property<long?>("exam_id")
                        .HasColumnName("exam_id");

                    b.HasIndex("exam_id")
                        .HasName("ix_score_formulas_exam_id");

                    b.ToTable("score_formulas");

                    b.HasDiscriminator().HasValue("ExamScoreFormula");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.CityModel.City", b =>
                {
                    b.OwnsOne("TestOkur.Domain.Model.Name", "Name", b1 =>
                        {
                            b1.Property<long>("CityId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("name_value")
                                .HasMaxLength(50)
                                .IsUnicode(true);

                            b1.HasKey("CityId")
                                .HasName("pk_cities");

                            b1.ToTable("cities");

                            b1.HasOne("TestOkur.Domain.Model.CityModel.City")
                                .WithOne("Name")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "CityId")
                                .HasConstraintName("fk_cities_cities_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TestOkur.Domain.Model.CityModel.District", b =>
                {
                    b.HasOne("TestOkur.Domain.Model.CityModel.City")
                        .WithMany("Districts")
                        .HasForeignKey("city_id")
                        .HasConstraintName("fk_districts_cities_city_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("TestOkur.Domain.Model.Name", "Name", b1 =>
                        {
                            b1.Property<long>("DistrictId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("name_value")
                                .HasMaxLength(150)
                                .IsUnicode(true);

                            b1.HasKey("DistrictId")
                                .HasName("pk_districts");

                            b1.ToTable("districts");

                            b1.HasOne("TestOkur.Domain.Model.CityModel.District")
                                .WithOne("Name")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "DistrictId")
                                .HasConstraintName("fk_districts_districts_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ClassroomModel.Classroom", b =>
                {
                    b.OwnsOne("TestOkur.Domain.Model.Grade", "Grade", b1 =>
                        {
                            b1.Property<long>("ClassroomId")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnName("grade_value");

                            b1.HasKey("ClassroomId")
                                .HasName("pk_classrooms");

                            b1.ToTable("classrooms");

                            b1.HasOne("TestOkur.Domain.Model.ClassroomModel.Classroom")
                                .WithOne("Grade")
                                .HasForeignKey("TestOkur.Domain.Model.Grade", "ClassroomId")
                                .HasConstraintName("fk_classrooms_classrooms_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TestOkur.Domain.Model.Name", "Name", b1 =>
                        {
                            b1.Property<long>("ClassroomId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("name_value")
                                .HasMaxLength(50)
                                .IsUnicode(true);

                            b1.HasKey("ClassroomId")
                                .HasName("pk_classrooms");

                            b1.ToTable("classrooms");

                            b1.HasOne("TestOkur.Domain.Model.ClassroomModel.Classroom")
                                .WithOne("Name")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "ClassroomId")
                                .HasConstraintName("fk_classrooms_classrooms_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ExamModel.Exam", b =>
                {
                    b.HasOne("TestOkur.Domain.Model.ExamModel.ExamBookletType", "ExamBookletType")
                        .WithMany()
                        .HasForeignKey("ExamBookletTypeId")
                        .HasConstraintName("fk_exams_exam_booklet_type_exam_booklet_type_id");

                    b.HasOne("TestOkur.Domain.Model.ExamModel.AnswerFormFormat", "AnswerFormFormat")
                        .WithMany()
                        .HasForeignKey("answer_form_format_id")
                        .HasConstraintName("fk_exams_answer_form_format_answer_form_format_id");

                    b.HasOne("TestOkur.Domain.Model.ExamModel.ExamType", "ExamType")
                        .WithMany()
                        .HasForeignKey("exam_type_id")
                        .HasConstraintName("fk_exams_exam_types_exam_type_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TestOkur.Domain.Model.LessonModel.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("lesson_id")
                        .HasConstraintName("fk_exams_lessons_lesson_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("TestOkur.Domain.Model.ExamModel.IncorrectEliminationRate", "IncorrectEliminationRate", b1 =>
                        {
                            b1.Property<long>("ExamId")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnName("incorrect_elimination_rate_value");

                            b1.HasKey("ExamId")
                                .HasName("pk_exams");

                            b1.ToTable("exams");

                            b1.HasOne("TestOkur.Domain.Model.ExamModel.Exam")
                                .WithOne("IncorrectEliminationRate")
                                .HasForeignKey("TestOkur.Domain.Model.ExamModel.IncorrectEliminationRate", "ExamId")
                                .HasConstraintName("fk_exams_exams_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TestOkur.Domain.Model.Name", "Name", b1 =>
                        {
                            b1.Property<long>("ExamId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("name_value")
                                .HasMaxLength(150)
                                .IsUnicode(true);

                            b1.HasKey("ExamId")
                                .HasName("pk_exams");

                            b1.ToTable("exams");

                            b1.HasOne("TestOkur.Domain.Model.ExamModel.Exam")
                                .WithOne("Name")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "ExamId")
                                .HasConstraintName("fk_exams_exams_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ExamModel.ExamScanSession", b =>
                {
                    b.HasOne("TestOkur.Domain.Model.ExamModel.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("exam_id")
                        .HasConstraintName("fk_exam_scan_sessions_exams_exam_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ExamModel.ExamType", b =>
                {
                    b.OwnsOne("TestOkur.Domain.Model.ExamModel.IncorrectEliminationRate", "DefaultIncorrectEliminationRate", b1 =>
                        {
                            b1.Property<long>("ExamTypeId")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnName("default_incorrect_elimination_rate_value");

                            b1.HasKey("ExamTypeId")
                                .HasName("pk_exam_types");

                            b1.ToTable("exam_types");

                            b1.HasOne("TestOkur.Domain.Model.ExamModel.ExamType")
                                .WithOne("DefaultIncorrectEliminationRate")
                                .HasForeignKey("TestOkur.Domain.Model.ExamModel.IncorrectEliminationRate", "ExamTypeId")
                                .HasConstraintName("fk_exam_types_exam_types_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TestOkur.Domain.Model.Name", "Name", b1 =>
                        {
                            b1.Property<long>("ExamTypeId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("name_value")
                                .HasMaxLength(100)
                                .IsUnicode(true);

                            b1.HasKey("ExamTypeId")
                                .HasName("pk_exam_types");

                            b1.ToTable("exam_types");

                            b1.HasOne("TestOkur.Domain.Model.ExamModel.ExamType")
                                .WithOne("Name")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "ExamTypeId")
                                .HasConstraintName("fk_exam_types_exam_types_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ExamModel.ExamTypeOpticalFormType", b =>
                {
                    b.HasOne("TestOkur.Domain.Model.ExamModel.ExamType")
                        .WithMany("ExamTypeOpticalFormTypes")
                        .HasForeignKey("ExamTypeId")
                        .HasConstraintName("fk_exam_type_optical_form_types_exam_types_exam_type_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TestOkur.Domain.Model.OpticalFormModel.OpticalFormType", "OpticalFormType")
                        .WithMany()
                        .HasForeignKey("optical_form_type_id")
                        .HasConstraintName("fk_exam_type_optical_form_types_optical_form_types_optical_for~")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TestOkur.Domain.Model.LessonModel.Lesson", b =>
                {
                    b.OwnsOne("TestOkur.Domain.Model.Name", "Name", b1 =>
                        {
                            b1.Property<long>("LessonId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("name_value")
                                .HasMaxLength(50)
                                .IsUnicode(true);

                            b1.HasKey("LessonId")
                                .HasName("pk_lessons");

                            b1.ToTable("lessons");

                            b1.HasOne("TestOkur.Domain.Model.LessonModel.Lesson")
                                .WithOne("Name")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "LessonId")
                                .HasConstraintName("fk_lessons_lessons_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TestOkur.Domain.Model.LessonModel.Subject", b =>
                {
                    b.HasOne("TestOkur.Domain.Model.LessonModel.Unit")
                        .WithMany("Subjects")
                        .HasForeignKey("unit_id")
                        .HasConstraintName("fk_subjects_units_unit_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("TestOkur.Domain.Model.Name", "Name", b1 =>
                        {
                            b1.Property<long>("SubjectId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("name_value")
                                .HasMaxLength(150)
                                .IsUnicode(true);

                            b1.HasKey("SubjectId")
                                .HasName("pk_subjects");

                            b1.ToTable("subjects");

                            b1.HasOne("TestOkur.Domain.Model.LessonModel.Subject")
                                .WithOne("Name")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "SubjectId")
                                .HasConstraintName("fk_subjects_subjects_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TestOkur.Domain.Model.LessonModel.Unit", b =>
                {
                    b.HasOne("TestOkur.Domain.Model.LessonModel.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .HasConstraintName("fk_units_lessons_lesson_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("TestOkur.Domain.Model.Grade", "Grade", b1 =>
                        {
                            b1.Property<long>("UnitId")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnName("grade_value");

                            b1.HasKey("UnitId")
                                .HasName("pk_units");

                            b1.ToTable("units");

                            b1.HasOne("TestOkur.Domain.Model.LessonModel.Unit")
                                .WithOne("Grade")
                                .HasForeignKey("TestOkur.Domain.Model.Grade", "UnitId")
                                .HasConstraintName("fk_units_units_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TestOkur.Domain.Model.Name", "Name", b1 =>
                        {
                            b1.Property<long>("UnitId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("name_value")
                                .HasMaxLength(150)
                                .IsUnicode(true);

                            b1.HasKey("UnitId")
                                .HasName("pk_units");

                            b1.ToTable("units");

                            b1.HasOne("TestOkur.Domain.Model.LessonModel.Unit")
                                .WithOne("Name")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "UnitId")
                                .HasConstraintName("fk_units_units_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TestOkur.Domain.Model.OpticalFormModel.FormLessonSection", b =>
                {
                    b.HasOne("TestOkur.Domain.Model.LessonModel.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("lesson_id")
                        .HasConstraintName("fk_form_lesson_sections_lessons_lesson_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TestOkur.Domain.Model.OpticalFormModel.OpticalFormType")
                        .WithMany("FormLessonSections")
                        .HasForeignKey("optical_form_type_id")
                        .HasConstraintName("fk_form_lesson_sections_optical_form_types_optical_form_type_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TestOkur.Domain.Model.OpticalFormModel.OpticalFormDefinition", b =>
                {
                    b.HasOne("TestOkur.Domain.Model.OpticalFormModel.Direction", "StudentNumberFillDirection")
                        .WithMany()
                        .HasForeignKey("StudentNumberFillDirectionId")
                        .HasConstraintName("fk_optical_form_definitions_directions_student_number_fill_dir~");

                    b.HasOne("TestOkur.Domain.Model.OpticalFormModel.Direction", "TextDirection")
                        .WithMany()
                        .HasForeignKey("TextDirectionId")
                        .HasConstraintName("fk_optical_form_definitions_directions_text_direction_id");

                    b.HasOne("TestOkur.Domain.Model.OpticalFormModel.OpticalFormType")
                        .WithMany("OpticalFormDefinitions")
                        .HasForeignKey("optical_form_type_id")
                        .HasConstraintName("fk_optical_form_definitions_optical_form_types_optical_form_ty~")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TestOkur.Domain.Model.SchoolType", "SchoolType")
                        .WithMany()
                        .HasForeignKey("school_type_id")
                        .HasConstraintName("fk_optical_form_definitions_school_types_school_type_id");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.OpticalFormModel.OpticalFormTextLocation", b =>
                {
                    b.HasOne("TestOkur.Domain.Model.OpticalFormModel.OpticalFormDefinition")
                        .WithMany("TextLocations")
                        .HasForeignKey("optical_form_definition_id")
                        .HasConstraintName("fk_optical_form_text_locations_optical_form_definitions_optica~")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("TestOkur.Domain.Model.OpticalFormModel.Location", "Class", b1 =>
                        {
                            b1.Property<long>("OpticalFormTextLocationId")
                                .HasColumnName("id");

                            b1.Property<int>("X")
                                .HasColumnName("class_x");

                            b1.Property<int>("Y")
                                .HasColumnName("class_y");

                            b1.HasKey("OpticalFormTextLocationId")
                                .HasName("pk_optical_form_text_locations");

                            b1.ToTable("optical_form_text_locations");

                            b1.HasOne("TestOkur.Domain.Model.OpticalFormModel.OpticalFormTextLocation")
                                .WithOne("Class")
                                .HasForeignKey("TestOkur.Domain.Model.OpticalFormModel.Location", "OpticalFormTextLocationId")
                                .HasConstraintName("fk_optical_form_text_locations_optical_form_text_locations_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TestOkur.Domain.Model.OpticalFormModel.Location", "ExamName", b1 =>
                        {
                            b1.Property<long>("OpticalFormTextLocationId")
                                .HasColumnName("id");

                            b1.Property<int>("X")
                                .HasColumnName("exam_name_x");

                            b1.Property<int>("Y")
                                .HasColumnName("exam_name_y");

                            b1.HasKey("OpticalFormTextLocationId")
                                .HasName("pk_optical_form_text_locations");

                            b1.ToTable("optical_form_text_locations");

                            b1.HasOne("TestOkur.Domain.Model.OpticalFormModel.OpticalFormTextLocation")
                                .WithOne("ExamName")
                                .HasForeignKey("TestOkur.Domain.Model.OpticalFormModel.Location", "OpticalFormTextLocationId")
                                .HasConstraintName("fk_optical_form_text_locations_optical_form_text_locations_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TestOkur.Domain.Model.OpticalFormModel.Location", "Name", b1 =>
                        {
                            b1.Property<long>("OpticalFormTextLocationId")
                                .HasColumnName("id");

                            b1.Property<int>("X")
                                .HasColumnName("name_x");

                            b1.Property<int>("Y")
                                .HasColumnName("name_y");

                            b1.HasKey("OpticalFormTextLocationId")
                                .HasName("pk_optical_form_text_locations");

                            b1.ToTable("optical_form_text_locations");

                            b1.HasOne("TestOkur.Domain.Model.OpticalFormModel.OpticalFormTextLocation")
                                .WithOne("Name")
                                .HasForeignKey("TestOkur.Domain.Model.OpticalFormModel.Location", "OpticalFormTextLocationId")
                                .HasConstraintName("fk_optical_form_text_locations_optical_form_text_locations_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TestOkur.Domain.Model.OpticalFormModel.Location", "StudentNo", b1 =>
                        {
                            b1.Property<long>("OpticalFormTextLocationId")
                                .HasColumnName("id");

                            b1.Property<int>("X")
                                .HasColumnName("student_no_x");

                            b1.Property<int>("Y")
                                .HasColumnName("student_no_y");

                            b1.HasKey("OpticalFormTextLocationId")
                                .HasName("pk_optical_form_text_locations");

                            b1.ToTable("optical_form_text_locations");

                            b1.HasOne("TestOkur.Domain.Model.OpticalFormModel.OpticalFormTextLocation")
                                .WithOne("StudentNo")
                                .HasForeignKey("TestOkur.Domain.Model.OpticalFormModel.Location", "OpticalFormTextLocationId")
                                .HasConstraintName("fk_optical_form_text_locations_optical_form_text_locations_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TestOkur.Domain.Model.OpticalFormModel.Location", "StudentNoFillingPart", b1 =>
                        {
                            b1.Property<long>("OpticalFormTextLocationId")
                                .HasColumnName("id");

                            b1.Property<int>("X")
                                .HasColumnName("student_no_filling_part_x");

                            b1.Property<int>("Y")
                                .HasColumnName("student_no_filling_part_y");

                            b1.HasKey("OpticalFormTextLocationId")
                                .HasName("pk_optical_form_text_locations");

                            b1.ToTable("optical_form_text_locations");

                            b1.HasOne("TestOkur.Domain.Model.OpticalFormModel.OpticalFormTextLocation")
                                .WithOne("StudentNoFillingPart")
                                .HasForeignKey("TestOkur.Domain.Model.OpticalFormModel.Location", "OpticalFormTextLocationId")
                                .HasConstraintName("fk_optical_form_text_locations_optical_form_text_locations_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TestOkur.Domain.Model.OpticalFormModel.Location", "Surname", b1 =>
                        {
                            b1.Property<long>("OpticalFormTextLocationId")
                                .HasColumnName("id");

                            b1.Property<int>("X")
                                .HasColumnName("surname_x");

                            b1.Property<int>("Y")
                                .HasColumnName("surname_y");

                            b1.HasKey("OpticalFormTextLocationId")
                                .HasName("pk_optical_form_text_locations");

                            b1.ToTable("optical_form_text_locations");

                            b1.HasOne("TestOkur.Domain.Model.OpticalFormModel.OpticalFormTextLocation")
                                .WithOne("Surname")
                                .HasForeignKey("TestOkur.Domain.Model.OpticalFormModel.Location", "OpticalFormTextLocationId")
                                .HasConstraintName("fk_optical_form_text_locations_optical_form_text_locations_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TestOkur.Domain.Model.OpticalFormModel.OpticalFormType", b =>
                {
                    b.HasOne("TestOkur.Domain.Model.SchoolType", "SchoolType")
                        .WithMany()
                        .HasForeignKey("SchoolTypeId")
                        .HasConstraintName("fk_optical_form_types_school_types_school_type_id");

                    b.OwnsOne("TestOkur.Domain.Model.Name", "Name", b1 =>
                        {
                            b1.Property<long>("OpticalFormTypeId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("name_value")
                                .HasMaxLength(100)
                                .IsUnicode(true);

                            b1.HasKey("OpticalFormTypeId")
                                .HasName("pk_optical_form_types");

                            b1.ToTable("optical_form_types");

                            b1.HasOne("TestOkur.Domain.Model.OpticalFormModel.OpticalFormType")
                                .WithOne("Name")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "OpticalFormTypeId")
                                .HasConstraintName("fk_optical_form_types_optical_form_types_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ScoreModel.LessonCoefficient", b =>
                {
                    b.HasOne("TestOkur.Domain.Model.ScoreModel.ScoreFormula")
                        .WithMany("Coefficients")
                        .HasForeignKey("ScoreFormulaId")
                        .HasConstraintName("fk_lesson_coefficients_score_formulas_score_formula_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TestOkur.Domain.Model.OpticalFormModel.FormLessonSection", "ExamLessonSection")
                        .WithMany()
                        .HasForeignKey("exam_lesson_section_id")
                        .HasConstraintName("fk_lesson_coefficients_form_lesson_sections_exam_lesson_sectio~");
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ScoreModel.ScoreFormula", b =>
                {
                    b.HasOne("TestOkur.Domain.Model.ScoreModel.FormulaType", "FormulaType")
                        .WithMany()
                        .HasForeignKey("FormulaTypeId")
                        .HasConstraintName("fk_score_formulas_formula_types_formula_type_id");

                    b.OwnsOne("TestOkur.Domain.Model.Grade", "Grade", b1 =>
                        {
                            b1.Property<long>("ScoreFormulaId")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnName("grade_value");

                            b1.HasKey("ScoreFormulaId")
                                .HasName("pk_score_formulas");

                            b1.ToTable("score_formulas");

                            b1.HasOne("TestOkur.Domain.Model.ScoreModel.ScoreFormula")
                                .WithOne("Grade")
                                .HasForeignKey("TestOkur.Domain.Model.Grade", "ScoreFormulaId")
                                .HasConstraintName("fk_score_formulas_score_formulas_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TestOkur.Domain.Model.Name", "Name", b1 =>
                        {
                            b1.Property<long>("ScoreFormulaId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("name_value")
                                .HasMaxLength(20)
                                .IsUnicode(true);

                            b1.HasKey("ScoreFormulaId")
                                .HasName("pk_score_formulas");

                            b1.ToTable("score_formulas");

                            b1.HasOne("TestOkur.Domain.Model.ScoreModel.ScoreFormula")
                                .WithOne("Name")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "ScoreFormulaId")
                                .HasConstraintName("fk_score_formulas_score_formulas_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TestOkur.Domain.Model.SettingModel.AppSetting", b =>
                {
                    b.OwnsOne("TestOkur.Domain.Model.Name", "Name", b1 =>
                        {
                            b1.Property<long>("AppSettingId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("name_value")
                                .HasMaxLength(100)
                                .IsUnicode(true);

                            b1.HasKey("AppSettingId")
                                .HasName("pk_appsettings");

                            b1.ToTable("appsettings");

                            b1.HasOne("TestOkur.Domain.Model.SettingModel.AppSetting")
                                .WithOne("Name")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "AppSettingId")
                                .HasConstraintName("fk_appsettings_appsettings_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TestOkur.Domain.Model.SmsModel.SmsGroup", b =>
                {
                    b.OwnsOne("TestOkur.Domain.Model.Name", "Name", b1 =>
                        {
                            b1.Property<long>("SmsGroupId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .HasColumnName("name_value");

                            b1.HasKey("SmsGroupId")
                                .HasName("pk_sms_groups");

                            b1.ToTable("sms_groups");

                            b1.HasOne("TestOkur.Domain.Model.SmsModel.SmsGroup")
                                .WithOne("Name")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "SmsGroupId")
                                .HasConstraintName("fk_sms_groups_sms_groups_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TestOkur.Domain.Model.StudentModel.Contact", b =>
                {
                    b.HasOne("TestOkur.Domain.Model.StudentModel.Student")
                        .WithMany("Contacts")
                        .HasForeignKey("student_id")
                        .HasConstraintName("fk_contacts_students_student_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("TestOkur.Domain.Model.Phone", "Phone", b1 =>
                        {
                            b1.Property<long>("ContactId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("phone_value")
                                .HasMaxLength(20);

                            b1.HasKey("ContactId")
                                .HasName("pk_contacts");

                            b1.ToTable("contacts");

                            b1.HasOne("TestOkur.Domain.Model.StudentModel.Contact")
                                .WithOne("Phone")
                                .HasForeignKey("TestOkur.Domain.Model.Phone", "ContactId")
                                .HasConstraintName("fk_contacts_contacts_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TestOkur.Domain.Model.StudentModel.Student", b =>
                {
                    b.HasOne("TestOkur.Domain.Model.ClassroomModel.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("classroom_id")
                        .HasConstraintName("fk_students_classrooms_classroom_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("TestOkur.Domain.Model.StudentNumber", "StudentNumber", b1 =>
                        {
                            b1.Property<long>("StudentId")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnName("student_number_value");

                            b1.HasKey("StudentId")
                                .HasName("pk_students");

                            b1.ToTable("students");

                            b1.HasOne("TestOkur.Domain.Model.StudentModel.Student")
                                .WithOne("StudentNumber")
                                .HasForeignKey("TestOkur.Domain.Model.StudentNumber", "StudentId")
                                .HasConstraintName("fk_students_students_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TestOkur.Domain.Model.Name", "FirstName", b1 =>
                        {
                            b1.Property<long>("StudentId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("first_name_value")
                                .HasMaxLength(50)
                                .IsUnicode(true);

                            b1.HasKey("StudentId")
                                .HasName("pk_students");

                            b1.ToTable("students");

                            b1.HasOne("TestOkur.Domain.Model.StudentModel.Student")
                                .WithOne("FirstName")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "StudentId")
                                .HasConstraintName("fk_students_students_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TestOkur.Domain.Model.Name", "LastName", b1 =>
                        {
                            b1.Property<long>("StudentId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("last_name_value")
                                .HasMaxLength(50)
                                .IsUnicode(true);

                            b1.HasKey("StudentId")
                                .HasName("pk_students");

                            b1.ToTable("students");

                            b1.HasOne("TestOkur.Domain.Model.StudentModel.Student")
                                .WithOne("LastName")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "StudentId")
                                .HasConstraintName("fk_students_students_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TestOkur.Domain.Model.UserModel.LicenseType", b =>
                {
                    b.OwnsOne("TestOkur.Domain.Model.Name", "Name", b1 =>
                        {
                            b1.Property<long>("LicenseTypeId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("name_value")
                                .HasMaxLength(150)
                                .IsUnicode(true);

                            b1.HasKey("LicenseTypeId")
                                .HasName("pk_license_types");

                            b1.ToTable("license_types");

                            b1.HasOne("TestOkur.Domain.Model.UserModel.LicenseType")
                                .WithOne("Name")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "LicenseTypeId")
                                .HasConstraintName("fk_license_types_license_types_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TestOkur.Domain.Model.UserModel.User", b =>
                {
                    b.HasOne("TestOkur.Domain.Model.CityModel.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .HasConstraintName("fk_users_cities_city_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TestOkur.Domain.Model.CityModel.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .HasConstraintName("fk_users_districts_district_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("TestOkur.Domain.Model.Email", "Email", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("email_value")
                                .HasMaxLength(255);

                            b1.HasKey("UserId")
                                .HasName("pk_users");

                            b1.ToTable("users");

                            b1.HasOne("TestOkur.Domain.Model.UserModel.User")
                                .WithOne("Email")
                                .HasForeignKey("TestOkur.Domain.Model.Email", "UserId")
                                .HasConstraintName("fk_users_users_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TestOkur.Domain.Model.Name", "FirstName", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("first_name_value")
                                .HasMaxLength(50)
                                .IsUnicode(true);

                            b1.HasKey("UserId")
                                .HasName("pk_users");

                            b1.ToTable("users");

                            b1.HasOne("TestOkur.Domain.Model.UserModel.User")
                                .WithOne("FirstName")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "UserId")
                                .HasConstraintName("fk_users_users_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TestOkur.Domain.Model.Name", "LastName", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("last_name_value")
                                .HasMaxLength(50)
                                .IsUnicode(true);

                            b1.HasKey("UserId")
                                .HasName("pk_users");

                            b1.ToTable("users");

                            b1.HasOne("TestOkur.Domain.Model.UserModel.User")
                                .WithOne("LastName")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "UserId")
                                .HasConstraintName("fk_users_users_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TestOkur.Domain.Model.Name", "RegistrarFullName", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("registrar_full_name_value")
                                .HasMaxLength(100)
                                .IsUnicode(true);

                            b1.HasKey("UserId")
                                .HasName("pk_users");

                            b1.ToTable("users");

                            b1.HasOne("TestOkur.Domain.Model.UserModel.User")
                                .WithOne("RegistrarFullName")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "UserId")
                                .HasConstraintName("fk_users_users_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TestOkur.Domain.Model.Name", "SchoolName", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("school_name_value")
                                .HasMaxLength(100)
                                .IsUnicode(true);

                            b1.HasKey("UserId")
                                .HasName("pk_users");

                            b1.ToTable("users");

                            b1.HasOne("TestOkur.Domain.Model.UserModel.User")
                                .WithOne("SchoolName")
                                .HasForeignKey("TestOkur.Domain.Model.Name", "UserId")
                                .HasConstraintName("fk_users_users_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TestOkur.Domain.Model.Phone", "Phone", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("phone_value")
                                .HasMaxLength(20);

                            b1.HasKey("UserId")
                                .HasName("pk_users");

                            b1.ToTable("users");

                            b1.HasOne("TestOkur.Domain.Model.UserModel.User")
                                .WithOne("Phone")
                                .HasForeignKey("TestOkur.Domain.Model.Phone", "UserId")
                                .HasConstraintName("fk_users_users_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("TestOkur.Domain.Model.Phone", "RegistrarPhone", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnName("registrar_phone_value")
                                .HasMaxLength(20);

                            b1.HasKey("UserId")
                                .HasName("pk_users");

                            b1.ToTable("users");

                            b1.HasOne("TestOkur.Domain.Model.UserModel.User")
                                .WithOne("RegistrarPhone")
                                .HasForeignKey("TestOkur.Domain.Model.Phone", "UserId")
                                .HasConstraintName("fk_users_users_id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("TestOkur.Domain.Model.ScoreModel.ExamScoreFormula", b =>
                {
                    b.HasOne("TestOkur.Domain.Model.ExamModel.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("exam_id")
                        .HasConstraintName("fk_score_formulas_exams_exam_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
